[project]
name = "torchpipe"
version = "0.1.24"

requires-python = ">=3.8"
description = "Serving inside Pytorch"
dependencies = [
    "torch",
    "omniback>=0.1.24",
    "setuptools",
    "packaging",
    "tqdm",
    "requests",
    "ninja",
    "cmake",
    "patchelf"
]

authors = [{ name = "TorchPipe Team" }]
readme = "README.md"
license = { text = "Apache-2.0" }
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Free Threading :: 2",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
keywords = ["pytorch", "inference", "tensorrt", "deep-learning", "serving"]

[project.urls]
Homepage = "https://github.com/torchpipe/torchpipe"
Documentation = "https://torchpipe.github.io/torchpipe/"
Repository = "https://github.com/torchpipe/torchpipe.git"
"Bug Tracker" = "https://github.com/torchpipe/torchpipe/issues"

[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools_scm[toml]>=6.2",
    "wheel",
    "ninja"
]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = [
    "onnx-graphsurgeon>=0.5.8",  
    "pytest",  
    'pillow',
    "tabulate",     
    'onnxslim',
]

[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
where = ["."]
include = ["torchpipe", "torchpipe.*"]
exclude = [
    "torchpipe.examples*",
    "torchpipe.exp*",
    "torchpipe.tests*",
]

[tool.setuptools.package-data]
"torchpipe" = [
    "*.py",
    "*.so", "*.dll", "*.dylib",
    "lib/*.so",
    "csrc/**/*",
]